# Generated by Django 5.2.5 on 2025-08-22 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='can_create',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_delete',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_read',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_update',
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='custom_auth_users', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='custom_auth_users', to='auth.permission'),
        ),
    ]
